### ISSUE TITLE
JMeter cannot be run in macOS Sonoma (Apple Silicon) by Homebrew

### ISSUE THREAD

**Issue by zzxrain** [apache/jmeter#6083]
### Expected behavior

Run jmeter successfully

### Actual behavior

JMeter crashed after display startup logo

<img width="258" alt="Screenshot 2023-10-06 at 15 29 48" src="https://github.com/apache/jmeter/assets/28227364/0020ba30-cd8a-4e7d-bf74-78cfc914cc13">

Below are defailed report.
[crash_report.log](https://github.com/apache/jmeter/files/12828247/crash_report.log)

### Steps to reproduce the problem

1. Install jmeter by homebrew (automatically install openJDK) 
```
brew install jmeter
```
2. run jmeter in terminal/iTerm2
```
jmeter
```
3. I re-tested it  by Amazon-Corretto-11 & 21, it is the same result.

It looks like no useful info in jmeter.log
[jmeter.log](https://github.com/apache/jmeter/files/12828204/jmeter.log)

### JMeter Version

5.6.2

### Java Version

11.0.20.1

### OS Version

macOS Sonoma Version 14.0 (23A344)

**Comment by vlsi** [comment]
@weisJ , do you think it might be Darklaf-related?

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x000000018749161c

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [6785]

Application Specific Information:
References to Carbon menus are disallowed with AppKit menu system (see rdar://101002625). Use instances of NSMenu and NSMenuItem directly instead.
```


@zzxrain , do you think you could try running without darklaf?
For instance:
Download sources, replace LAF as follows:

```diff
--- a/src/core/src/main/java/org/apache/jmeter/gui/action/LookAndFeelCommand.java
+++ b/src/core/src/main/java/org/apache/jmeter/gui/action/LookAndFeelCommand.java
@@ -172,7 +172,7 @@ public class LookAndFeelCommand extends AbstractAction {
      * @return command that would activate the preferred LaF
      */
     public static String getPreferredLafCommand() {
-        String laf = PREFS.get(USER_PREFS_KEY, null);
+        String laf = "laf:com.apple.laf.AquaLookAndFeel";
         if (laf != null) {
             return laf;
         }
```

Start JMeter with `./gradlew runGui`

Will it launch?

**Comment by weisJ** [comment]
I’ll have a look. However the native menu bar used in darklaf is simply the one provided by the jdk, so I’m not sure how much I can do about it.

**Comment by zzxrain** [comment]
> @weisJ , do you think it might be Darklaf-related?
> 
> ```
> Crashed Thread:        0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:        EXC_BREAKPOINT (SIGTRAP)
> Exception Codes:       0x0000000000000001, 0x000000018749161c
> 
> Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
> Terminating Process:   exc handler [6785]
> 
> Application Specific Information:
> References to Carbon menus are disallowed with AppKit menu system (see rdar://101002625). Use instances of NSMenu and NSMenuItem directly instead.
> ```
> 
> @zzxrain , do you think you could try running without darklaf? For instance: Download sources, replace LAF as follows:
> 
> ```diff
> --- a/src/core/src/main/java/org/apache/jmeter/gui/action/LookAndFeelCommand.java
> +++ b/src/core/src/main/java/org/apache/jmeter/gui/action/LookAndFeelCommand.java
> @@ -172,7 +172,7 @@ public class LookAndFeelCommand extends AbstractAction {
>       * @return command that would activate the preferred LaF
>       */
>      public static String getPreferredLafCommand() {
> -        String laf = PREFS.get(USER_PREFS_KEY, null);
> +        String laf = "laf:com.apple.laf.AquaLookAndFeel";
>          if (laf != null) {
>              return laf;
>          }
> ```
> 
> Start JMeter with `./gradlew runGui`
> 
> Will it launch?

I just pull the project and run it without any change, it is successfully.
It looks like 5.6.3 version, no reproducible.
The 5.6.2 from homebrew is the same error.
<img width="1206" alt="Screenshot 2023-10-07 at 08 42 49" src="https://github.com/apache/jmeter/assets/28227364/d0f72aff-2dbf-4f8a-97b6-4cb407a79852">

**Comment by ShanChathusanda93** [comment]
Facing the same issue. Anyone know a release timeline for the 5.6.3 because seems like the issue is fixed in there (based on the above comment)?

**Comment by vlsi** [comment]
Could you please try downloading and running 5.6.2 from https://jmeter.apache.org/download_jmeter.cgi to rule out homebrew packaging issue?

**Comment by zzxrain** [comment]
> Could you please try downloading and running 5.6.2 from https://jmeter.apache.org/download_jmeter.cgi to rule out homebrew packaging issue?

Yes, you are right, the binary from Apache Website is working.
I think it is related OpenJDK bundled with Homebrew.
I see it always imports JAVA_HOME by OpenJDK in /opt/homebrew/Cellar/jmeter/5.6.2/bin/jmeter
```
#!/bin/bash
JAVA_HOME="/opt/homebrew/opt/openjdk@17" exec "/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter"  "$@"
```
After edited as below, it works.
```
#!/bin/bash
exec "/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter"  "$@"
```

**Comment by andrekiba** [comment]
the same fix as @zzxrain doesn't work for me, m1 with Sonoma

- installed jmeter using homebrew
- installed the openjdk@21 with homebrew
- changed the jmeter file like this

`#!/bin/bash
JAVA_HOME="/opt/homebrew/opt/openjdk@21" exec "/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter"  "$@"`

if I try to download from [ https://jmeter.apache.org/download_jmeter.cgi ](https://jmeter.apache.org/download_jmeter.cgi) I have the same issue

Any help?

**Comment by zzxrain** [comment]
> the same fix as @zzxrain doesn't work for me, m1 with Sonoma
> 
> * installed jmeter using homebrew
> * installed the openjdk@21 with homebrew
> * changed the jmeter file in this way
>   `#!/bin/bash JAVA_HOME="/opt/homebrew/opt/openjdk@21" exec "/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter"  "$@"`
> 
> if I remove the `JAVA_HOME` from the file I still have the same issue
> 
> if I try to download from [ https://jmeter.apache.org/download_jmeter.cgi ](https://jmeter.apache.org/download_jmeter.cgi) I have the same issue
> 
> Any help?

Hi, could you try with amazon-corretto instead of JDK provided by homebrew ?

**Comment by joshelson** [comment]
Same issue for me here, but manually running this:

`JAVA_HOME="/opt/homebrew/opt/openjdk@21" exec "/opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter"`

So far seems to be OK.

**Comment by hendisantika** [comment]
I have same issue:

1. openJDK 21 using sdkman
2. Sonoma 14.0
3. brew install jmeter

I executed success in this link https://jmeter.apache.org/download_jmeter.cgi
but it's have to know binary file path for execute.
is there any other way? ✏️📗:octocat:⬆

Thanks

**Comment by belt** [comment]
```sh
uname -r # => 23.1.0
uname -m # => arm64
brew install corretto
JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter # => successful launch on an M1
```

**Comment by jourquin** [comment]
The problem seems to appear for any java app that uses the native macOS "Screen menu bars" setting
```
System.setProperty("apple.laf.useScreenMenuBar", "true");
```
This affects macOS Sonoma systems with a Homebrew OpenJDK. 

A quick and dirty fix (in the java code) is to avoid setting this property on affected systems. A example can be found at the end of the following code :
https://github.com/jourquin/Nodus/blob/master/src/edu/uclouvain/core/nodus/Nodus.java

**Comment by pmedish1** [comment]
> ```shell
> uname -r # => 23.1.0
> uname -m # => arm64
> brew install corretto
> 
> # => successful launch on an M1
> JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter
> ```

Tried this but did not work for me

**Comment by RukshanJS** [comment]
> ```shell
> uname -r # => 23.1.0
> uname -m # => arm64
> brew install corretto
> 
> # => successful launch on an M1
> JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter
> ```

After so much hours wasted on this. This is the only solution that really worked. Thanks!

**Comment by hendisantika** [comment]
uname -r # => 23.0.1
uname -m # => arm64
brew install corretto

It doesn't work for me

**Comment by RukshanJS** [comment]
> uname -r # => 23.0.1 uname -m # => arm64 brew install corretto
> 
> It doesn't work for me

what issue are you facing? "doesn't work" is not enough to help out.

**Comment by hendisantika** [comment]
JMeter not running after I installed those things @RukshanJS ...

**Comment by Forfend** [comment]
> ```shell
> uname -r # => 23.1.0
> uname -m # => arm64
> brew install corretto
> 
> # => successful launch on an M1
> JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter
> ```

will it work if I use sdkman to manage Java versions?

**Comment by hendisantika** [comment]
I am using SDKMAN. But still doesn't work

**Comment by RukshanJS** [comment]
I'll try to make a small tutorial on this. LMK if you can't still get it working.

**Comment by hendisantika** [comment]
> I'll try to make a small tutorial on this. LMK if you can't still get it working.

I can't wait for it.

Thanks

**Comment by Oesoto** [comment]
Running the long command

`JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter`

Works for me. Is there any way to make it work by just calling the `jmeter` command?

**Comment by RukshanJS** [comment]
@hendisantika @Oesoto I have covered the fix (including how to run with just `jmeter` command) on my youtube channel. Check it out and let me know comments. Also if it helps, kindly post comments over there.

https://youtu.be/5OlvuWOAu7o?si=paDMiE_XXN5o7Uyl

Happy testing!

**Comment by hendisantika** [comment]
OK Good. Thanks @RukshanJS

**Comment by hendisantika** [comment]
Well done. Thanks a lot @RukshanJS 

Now, It's working

**Comment by RukshanJS** [comment]
> Well done. Thanks a lot @RukshanJS 
> 
> Now, It's working

Awesome! Super glad it helped. Feedback much appreciated

**Comment by Oesoto** [comment]
@RukshanJS 

Thanks. Everything is working fine now.

I found this issue when setting up a new M3 machine. 

I also use a M1 machine that I've used with Jmeter 5.4.3 for a long time and I recently updated it from Ventura to Sonoma and Jmeter continued working normally without the need to install `corretto`. So maybe downgrading to an older version can be another possible workaround.

**Comment by mariasu11** [comment]
> @hendisantika @Oesoto I have covered the fix (including how to run with just `jmeter` command) on my youtube channel. Check it out and let me know comments. Also if it helps, kindly post comments over there.
> 
> https://youtu.be/5OlvuWOAu7o?si=paDMiE_XXN5o7Uyl
> 
> Happy testing!
> 
> P.S. - just published the video and would take some time to process to higher qualities.

This worked for me!!! Thank you!

**Comment by ca-milin15** [comment]
> > ```shell
> > uname -r # => 23.1.0
> > uname -m # => arm64
> > brew install corretto
> > 
> > # => successful launch on an M1
> > JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter
> > ```
> 
> After so much hours wasted on this. This is the only solution that really worked. Thanks! 🎉

It worked very well for me. Thanks so much.
PD: I have Sonoma 14.1.2 and M1 chip

**Comment by zzxrain** [comment]
This issue is fixed by latest Homebrew, hence close it.

**Comment by prineshaz** [comment]
> ```shell
> uname -r # => 23.1.0
> uname -m # => arm64
> brew install corretto
> 
> # => successful launch on an M1
> JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter
> ```

This worked, however i jmeter version was updated since, so changed /opt/homebrew/Cellar/jmeter/**5.6.2**/libexec/bin/jmeter to **5.6.3**, please note the jmeter version and apply accordingly.

**Comment by paulpacaud** [comment]
> ```shell
> JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home/ exec /opt/homebrew/Cellar/jmeter/5.6.2/libexec/bin/jmeter
> ```

wrong, the issue is still existing as of August, the 16th, 2024 :(

**Comment by paulpacaud** [comment]
> This issue is fixed by latest Homebrew, hence close it.

wrong, the issue is still existing as of August, the 16th, 2024 :(

**Comment by paulpacaud** [comment]
I fixed the issue uninstalling the package using brew uninstall jmeter, and then installing manually jmeter following this youtube tutorial:
https://www.youtube.com/watch?v=tPKe6eYnlUk
